# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Learned...
email: your-email@domain.com
description: I want to capture at least one piece of new information I learn every single day. I'll write about it here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: clapinton
github_username:  clapinton

# Build settings
markdown: kramdown
